name: Delete Packages from Pypi

description: Delete Packages from Pypi

inputs:
  user:
    required: true
  password:
    required: true
  package:
    required: true
  url:
    required: false
  dry-run:
    required: false
    default: 'true'
  days:
    required: false
    default: '0'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user }}
    - ${{ inputs.password }}
    - ${{ inputs.package }}
    - ${{ inputs.url }}
    - ${{ inputs.dry-run }}
    - ${{ inputs.days }}
