name: Delete Packages from Pypi

description: Delete Packages from Pypi

inputs:
  user:
    required: true
  password:
    required: true
  package:
    required: true
  url:
    required: false
  dry-run:
    default: true

runs:
  using: "composite"
  steps:
    - name: "Get releases"
      run: |
        wget ${{ inputs.package }}/${{ inputs.package }}/json
        python -c "import json; with open('json', 'r') as json_file: j = json.load(json_file);"
    - run: pypi-cleanup --username ${{ inputs.user }} --package ${{ inputs.package}}
