name: Delete Packages from Pypi

description: Delete Packages from Pypi

inputs:
  user:
    required: true
  password:
    required: true
  package:
    required: true
  url:
    required: false
  dry_run:
    required: false
    default: 'true'
  days:
    required: false
    default: '0'

runs:
  using: 'docker'
  image: 'Dockerfile'
